# Site settings
title: Widhi & Era
email: widhi.surya.atman@gmail.com
url: https://mwsatman.github.io
description: "Pawiwahan: Rabu, 8 April 2020"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#fff6f6' #'#000'
  def-font: '#000'
  links: '#219ab3'

  # header - title color
  title-font1: '#ffa07a' 
  # header - description color
  title-font2: '#ff6347' 
  title-fontnav: '#ff5447' #'#800026' 

# List of color
# black --> #000 
# white --> #fff


# Footer settings
footer: WE_dding

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: https://twitter.com/SBootstrap
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
